=== vix-4800/Workstation/phpcs/phpcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string" />
                <xs:element name="arg" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" />
                        <xs:attribute name="value" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="config" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="value" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="file" type="xs:string" />
                <xs:element name="rule" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="properties" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="property" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:ID"
                                                    use="required" />
                                                <xs:attribute name="value" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="0" />
                                                            <xs:enumeration value="1" />
                                                            <xs:enumeration value="10" />
                                                            <xs:enumeration value="120" />
                                                            <xs:enumeration value="4" />
                                                            <xs:enumeration value="80" />
                                                            <xs:enumeration value="false" />
                                                            <xs:enumeration value="true" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ref" type="xs:ID" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vix-4800/Workstation/php/phpcs.xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    name="Project Coding Standard"
    xsi:noNamespaceSchemaLocation="vendor/squizlabs/php_codesniffer/phpcs.xsd">

    <description>Project coding standard based on PSR-12.</description>

    <!-- ===== GENERAL ===== -->
    <arg name="parallel" value="8" />
    <arg name="extensions" value="php" />
    <config name="encoding" value="utf-8" />
    <config name="tabWidth" value="4" />
    <arg name="colors" />
    <arg value="p" />
    <arg name="basepath" value="." />
    <file>./</file>

    <!-- ===== CORE ===== -->
    <rule ref="PSR12" />

    <!-- ===== IMPORTS ===== -->
    <rule ref="SlevomatCodingStandard.Namespaces.UnusedUses" />
    <rule ref="SlevomatCodingStandard.Namespaces.MultipleUsesPerLine" />
    <rule ref="SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses">
        <properties>
            <property name="psr12Compatible" value="true" />
            <property name="caseSensitive" value="false" />
        </properties>
    </rule>
    <rule ref="SlevomatCodingStandard.Namespaces.UseSpacing">
        <properties>
            <property name="linesCountBetweenUseTypes" value="1" />
        </properties>
    </rule>
    <rule ref="SlevomatCodingStandard.Namespaces.ReferenceUsedNamesOnly">
        <properties>
            <property name="allowFullyQualifiedGlobalClasses" value="false" />
            <property name="allowFullyQualifiedGlobalFunctions" value="false" />
            <property name="allowFullyQualifiedGlobalConstants" value="false" />
            <property name="allowFullyQualifiedNameForCollidingClasses" value="true" />
            <property name="searchAnnotations" value="true" />
        </properties>
    </rule>

    <!-- ===== METRICS ===== -->
    <rule ref="Generic.Metrics.CyclomaticComplexity">
        <properties>
            <property name="complexity" value="10" />
        </properties>
    </rule>
    <rule ref="Generic.Metrics.NestingLevel">
        <properties>
            <property name="nestingLevel" value="4" />
        </properties>
    </rule>
    <rule ref="Squiz.Functions.FunctionLength">
        <properties>
            <property name="maxLength" value="80" />
            <property name="absoluteMaximum" value="120" />
        </properties>
    </rule>

    <!-- ===== TYPE_HINTS ===== -->
    <rule ref="SlevomatCodingStandard.TypeHints.DeclareStrictTypes">
        <properties>
            <property name="spacesCountAroundEqualsSign" value="0" />
            <property name="linesCountBeforeDeclare" value="1" />
            <property name="linesCountAfterDeclare" value="1" />
            <property name="declareOnFirstLine" value="false" />
        </properties>
    </rule>
    <rule ref="SlevomatCodingStandard.TypeHints.ParameterTypeHint" />
    <rule ref="SlevomatCodingStandard.TypeHints.ReturnTypeHint" />
    <rule ref="SlevomatCodingStandard.TypeHints.PropertyTypeHint" />
    <rule ref="SlevomatCodingStandard.TypeHints.NullableTypeForNullDefaultValue" />
    <rule ref="SlevomatCodingStandard.Operators.DisallowEqualOperators" />
    <rule ref="SlevomatCodingStandard.TypeHints.DisallowMixedTypeHint" />

    <!-- ===== RETURN TYPES ===== -->
    <rule ref="PSR12.Functions.ReturnTypeDeclaration" />
    <rule ref="PSR12.Functions.NullableTypeDeclaration" />
    <rule ref="Squiz.Functions.FunctionDeclaration" />
    <rule ref="Squiz.Functions.FunctionDeclarationArgumentSpacing">
        <properties>
            <property name="equalsSpacing" value="1" />
            <property name="requiredSpacesAfterOpen" value="0" />
            <property name="requiredSpacesBeforeClose" value="0" />
        </properties>
    </rule>

    <!-- ===== OPERATORS/WHITESPACES ===== -->
    <rule ref="Squiz.WhiteSpace.OperatorSpacing" />
    <rule ref="Squiz.Strings.ConcatenationSpacing">
        <properties>
            <property name="spacing" value="1" />
        </properties>
    </rule>
    <rule ref="SlevomatCodingStandard.Operators.NegationOperatorSpacing" />
    <rule ref="SlevomatCodingStandard.Operators.SpreadOperatorSpacing" />
    <rule ref="Generic.Formatting.SpaceAfterCast" />
    <rule ref="Squiz.WhiteSpace.SuperfluousWhitespace" />
    <rule ref="Generic.WhiteSpace.DisallowTabIndent" />
    <rule ref="Generic.Files.EndFileNewline" />
    <rule ref="Squiz.Strings.DoubleQuoteUsage" />

    <!-- ===== CONTROL STRUCTURES ===== -->
    <rule ref="SlevomatCodingStandard.ControlStructures.DisallowYodaComparison" />
    <rule ref="SlevomatCodingStandard.ControlStructures.EarlyExit" />
    <rule ref="SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator" />

    <!-- ===== ARRAYS/ARGUMENTS ===== -->
    <rule ref="Generic.Arrays.DisallowLongArraySyntax" />
    <rule ref="SlevomatCodingStandard.Arrays.TrailingArrayComma" />

    <!-- ===== CLASSES/MEMBERS ===== -->
    <rule ref="SlevomatCodingStandard.Classes.ClassMemberSpacing">
        <properties>
            <property name="linesCountBetweenMembers" value="1" />
        </properties>
    </rule>

    <!-- ===== DOCUMENTATION ===== -->
    <rule ref="SlevomatCodingStandard.Commenting.UselessFunctionDocComment" />
    <rule ref="SlevomatCodingStandard.Commenting.RequireOneLineDocComment" />
    <rule ref="SlevomatCodingStandard.Commenting.DocCommentSpacing" />

    <!-- ===== MISC ===== -->
    <rule ref="Generic.Files.LineLength">
        <properties>
            <property name="lineLimit" value="120" />
            <property name="absoluteLineLimit" value="0" />
            <property name="ignoreComments" value="true" />
        </properties>
    </rule>
    <rule ref="SlevomatCodingStandard.Functions.StaticClosure" />
    <rule ref="Generic.CodeAnalysis.AssignmentInCondition" />
    <rule ref="Generic.CodeAnalysis.EmptyStatement" />
</ruleset>
